- name: Teachbase | Update Admin app
  sudo: no
  git: repo={{ ng_app_repo }}
       version={{ ng_app_version }}
       accept_hostkey=yes
       depth=1
       dest={{ ng_app_path }}
       force=true
  notify:
    - Restart Nginx
