---
- name: Development setup
  hosts: development
  user: vagrant
  sudo: true
  roles:
    - { role: 'palkan.common_setup', tags: ['common'] }
    - { role: 'palkan.ruby', tags: ['ruby'] }
    - { role: 'palkan.postgresql', tags: ['postgres'] }
    - { role: 'palkan.redis', tags: ['redis'] }
    - { role: 'palkan.nodejs', tags: ['nodejs'] }
    - { role: 'palkan.ffmpeg', tags: ['ffmpeg']}
    - { role: 'palkan.erlang', tags: ['erlang'] }
    - { role: 'palkan.aws_cli', tags: ['aws_cli'] }
    - { role: 'palkan.varnish', tags: ['varnish'] }
