---
- name: EC2 production
  hosts: aws-production
  sudo: yes 
  remote_user: ubuntu
  vars_files:
    - group_vars/production.yml
    - aws.yml
    - fyler.yml
  gather_facts: True
  roles:
    - common_setup
    - deploy_user
    - ruby
    - postgres
    - redis
    - nodejs
    - erlang
    - erlyvideo
    - aws_cli
    - nginx
    - tb_prepare