---
- name: Development setup
  hosts: development
  user: vagrant
  sudo: true
  vars_files:
    - group_vars/development.yml
    - aws.yml
  roles:
    - { role: common_setup, tags: ['initial'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: postgres, tags: ['postgres'] }
    - { role: redis, tags: ['redis'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: erlang, tags: ['erlang'] }
    - { role: erlyvideo, tags: ['erlyvideo'] }
    - { role: aws_cli, tags: ['aws_cli'] }