---
varnish_vcl_name: "default.vcl"
varnish_vcl_dir: "/etc/varnish"
varnish_vcl_path: "{{varnish_vcl_dir}}/{{varnish_vcl_name}}"


# Open files (usually 1024, which is way too small for varnish).
varnish_ulimit: 131072

# Maxiumum locked memory size for shared memory log.
varnish_memlock: 82000

varnish_listen_port: 80
varnish_admin_port: 6082
varnish_malloc_size: 1G