- name: Install PostgreSQL contrib
  apt: pkg=postgresql-contrib-9.3 state=latest

- name: setup database
  sudo_user: postgres
  postgresql_db:
    db: "{{ pg_db }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: Install hstore ext
  sudo_user: postgres
  shell: psql {{ pg_db }} -c "CREATE EXTENSION IF NOT EXISTS hstore;"