- name: Erly | Create erly service
  action: template src=erly dest=/etc/init.d/erly mode=755

- name: Erly | Setup cron reboot task to start erly
  sudo_user: "{{ deploy_user }}"
  cron: name="start erly" special_time=reboot job="/bin/bash -l -c 'service erly start'"
