- name: Erly | clone 
  sudo_user: "{{ deploy_user }}"
  git: repo={{ erly_repo }}
       version={{ erly_version }}
       key_file={{ erly_key_file }}
       dest={{ erly_path }}
       force=true
  register: repo
  tags: erly_clone

- name: Erly | Copy configs
  sudo_user: "{{ deploy_user }}"
  template: src={{ item.src }} dest={{ item.dest }}
  with_items: erly_configs
  register: configs
  tags: erly_configs

- name: Erly | release exists?
  stat: path={{ erly_bin_path }}/{{ erly_bin_name }}
  register: release_bin
  tags: erly_release

- name: Erly | clean
  sudo_user: "{{ deploy_user }}"
  command: make clean chdir={{ erly_path }}
  when: erly_force_clean or repo.changed or configs.changed or (not release_bin.stat.exists)
  register: cleaned

- name: Erly | remove deps
  sudo_user: "{{ deploy_user }}"
  file: path={{ erly_path }}/deps state=absent
  when: erly_force_clean

- name: Erly | update deps and compile
  sudo_user: "{{ deploy_user }}"
  environment: ffmpeg_env
  command: make {{ item }} chdir={{ erly_path }}
  when: cleaned.changed
  with_items:
    - get-lager
    - get-deps
    - update-deps
    - compile
  register: compiled

- name: Erly | stop
  service: name=erlyd state=stopped
  when: erly_force_release
  tags: erly_release

- name: Erly | release
  sudo_user: "{{ deploy_user }}"
  command: make soft-release chdir={{ erly_path }}
  when: erly_force_release or (compiled is defined and compiled.changed) or (release_bin is defined and (not release_bin.stat.exists))
  tags: erly_release
  notify:
    - Restart Erly
