- name: Erly | Create the Github SSH public key file
  copy: src="{{ erly_public_key }}"
        dest="/home/{{ deploy_user }}/.ssh/id_rsa.pub"
        mode=0644
        owner="{{ deploy_user }}"
        group="{{ deploy_user }}"

- name: Create the Github SSH private key file
  copy: src="{{ erly_private_key }}"
        dest="/home/{{ deploy_user }}/.ssh/id_rsa"
        mode=0600
        owner="{{ deploy_user }}"
        group="{{ deploy_user }}"